worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # 1. Format logs as JSON so Kibana can read them easily
    log_format json_logs escape=json
    '{'
        '"timestamp":"$time_iso8601",'
        '"service":"lawracle-frontend",'
        '"level":"INFO",'
        '"client_ip":"$http_x_forwarded_for",'
        '"method":"$request_method",'
        '"path":"$request_uri",'
        '"status":$status,'
        '"user_agent":"$http_user_agent"'
    '}';

    access_log /dev/stdout json_logs;
    access_log syslog:server=logstash.logging.svc.cluster.local:5045,tag=nginx json_logs;
    error_log  /dev/stderr warn;

    server {
        listen 80;

        # 2. Serve your index.html file for normal webpage visits
        location / {
            root   /usr/share/nginx/html;
            index  index.html;
            try_files $uri $uri/ /index.html;
        }

        # 3. Intercept any requests to /api/ and silently forward them to the backend pod
        location /api/ {
            # Give the CPU-bound AI model up to 10 minutes (600 seconds) to reply
            proxy_read_timeout 600s;
            proxy_connect_timeout 600s;
            proxy_send_timeout 600s;
            
            proxy_pass http://lawracle-backend-service.default.svc.cluster.local:5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}